fabric_name: DC1_FABRIC

underlay_p2p_network_summary: 172.16.10.0/24

overlay_loopback_network_summary: 120.0.0.0/24

vtep_loopback_network_summary: 110.0.0.0/24

vxlan_vlan_aware_bundles: true

bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
    password: "q+VNViP5i4rVjW1cxFv2wA=="

spine:
  platform: vEOS-LAB
  bgp_as: 65001
  leaf_as_range: 65101-65132
  nodes:
    DC1-SPINE1:
      id: 1
      mgmt_ip: 192.168.26.111/24

l3leaf:
  defaults:
    platform: vEOS-LAB
    spines: [ DC1-SPINE1 ]
    bgp_as: 65100
    uplink_to_spine_interfaces: [ Ethernet1 ]
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    virtual_router_mac_address : aa:aa:bb:bb:cc:cc
  node_groups:
    DC1_LEAF1:
      bgp_as: 65101
      nodes:
        DC1-LEAF1A:
          id: 1
          mgmt_ip: 192.168.26.112/24
          spine_interfaces: [ Ethernet1 ]
    DC1_LEAF2:
      bgp_as: 65102
      nodes:
        DC1-LEAF2A:
          id: 2
          mgmt_ip: 192.168.26.113/24
          spine_interfaces: [ Ethernet1 ]

spine_bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

leaf_bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

p2p_uplinks_mtu: 1500
